[build]
base = '/'
command = 'pnpm run netlify-build'
publish = 'docs/dist'
functions = 'docs/.netlify/functions-internal'

[build.environment]
NODE_VERSION = '24'
NODE_OPTIONS = --max-old-space-size=4096
